### ISSUE TITLE
Scrubbing preview disappears after interacting with media controls

### ISSUE THREAD

**Issue by LeviSnoot** [nicknsy/jellyscrub#10]
https://user-images.githubusercontent.com/13402525/182369162-1eeb1903-30f2-4700-9ac3-9fdd3bee6fa3.mp4

Having an interesting bug where if I interact with the media controls (subtitle, bitrate audio menu etc) the scrubbing disappears until I close the stream and reopen it.

Server version 10.8.3 running on Windows 11. I've tried disabling custom css, it still reproduces so it isn't that.

**Comment by nicknsy** [comment]
Did you have the plugin installed before 10.8.3 and if so did this still occur on versions before then?

**Comment by LeviSnoot** [comment]
I had it on 10.8.1 but I just installed the plugin yesterday and it's still building the .bif files so I didn't check before.

**Comment by nicknsy** [comment]
Yup this is also happening for me with any button that opens up a menu selection like subtitles, settings, etc. Will have to look into whats causing it as it isn't immediately apparent

**Comment by nicknsy** [comment]
Nevermind it is. Likely caused by 1.0.0.1 disconnecting the slider observer on popstate. Will fix with 1.0.0.2 within the next hour.
