### ISSUE TITLE
No Jellyscrub preview images in webOS-client despite latest Update 

### ISSUE THREAD

**Issue by Git-Boy-Slim** [nicknsy/jellyscrub#101]
Jellyscrub works for me in the normal web UI and on my Android client, but unfortunately it won't do it's magic in the webOS-client on my LG TV. 

Somehow nicknsy and I thought we would have a fix for that with the latest update, which merged the [pull request](https://github.com/nicknsy/jellyscrub/pull/58) from @NeroPcStation , but it didn't do the trick for me. 
I previously asked about this issue on [reddit](https://www.reddit.com/r/jellyfin/comments/wyke8p/comment/jbt2pts/) so I know that nicknsy can't do much more about that. 

But I hope that there is someone else, who could help me with this problem and maybe someday I will be able to see the glory of Jellyscrub working on my TV. 

FYI: 
I use the webOS-client v 1.1.2 from LGs content store. 
My TV is a LG OLED55CX9LA and runs webOS version 5.4.2-25. 
And other Plugins like the Intro Skipper or Custom CSS, as well as the native chapter preview images from Jellyfin indeed do work on my webOS-client.

**Comment by Git-Boy-Slim** [comment]
I've tested the fix from @NeroPcStation and can happily confirm it's working flawlessly for me. It's awesome how fast this problem was solved. Thank you very very much!

Do I need to close this issue now or shall I wait until it is merged into the main branch? @nicknsy

**Comment by nicknsy** [comment]
You can leave it open. Glad you got it working!
