### ISSUE TITLE
Create multiple file at same time

### ISSUE THREAD

**Issue by Gauvino** [nicknsy/jellyscrub#105]
Hello, do you think it's possible when hardware acceleration enables to encode multiple file at the same time to increase speed?

**Comment by nicknsy** [comment]
This was discussed in #77, but kura was unable to see any significant gain with multiple ffmpeg processes running in parallel on their Quadro card. Whether that's a limit of ffmpeg's implementation, mine, or if the overall usage reported did not accurately reflect the usage of encode/decode specifically is something I'm unsure of. For now, it looks to be something that would be difficult to implement for not much immediate value.

**Comment by Uruknara** [comment]
Oh ok no problem I should watch discussion before sorry

**Comment by nicknsy** [comment]
> Oh ok no problem I should watch discussion before sorry 

Don't worry about it. It was quite an old issue that had already been closed.

**Comment by verbumfeit** [comment]
Multiple ffmpeg processes do help with speed, at least on Intel HD integrated graphics:

With one ffmpeg process:
![image](https://github.com/nicknsy/jellyscrub/assets/4244402/b515a120-39cd-4768-8756-bb22331179fe)

With two ffmpeg processes:
![image](https://github.com/nicknsy/jellyscrub/assets/4244402/f01208cc-c485-4f97-b96f-f0b6ea566f5d)

Both executed with this command (copied from ps output):
```/usr/lib/jellyfin-ffmpeg/ffmpeg -loglevel error -init_hw_device vaapi=va:/dev/dri/renderD128,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i "file:/mnt/nas/movie.mp4" -autoscale 0 -an -sn -vf fps=1/10,setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=w=320:h=180:format=nv12:extra_hw_frames=24,hwmap=mode=read,format=nv12 -threads 0 -c:v mjpeg -f image2 /tmp/img_%08d.jpg```

It seems to me that the iGPU has two cores/threads and we only use one with our ffmpeg process.

Seeing as this basically doubles the speed, Jellyscrub could run with two ffmpeg processes as long as ```driver=iHD```. Or the number of concurrent ffmpeg processes could/should be made configurable. With a hint that it may not increase speed when you're on a non-Intel HD graphics.
