### ISSUE TITLE
Bug and Solution: trickplay folder appear on TV/Anime without season folder.

### ISSUE THREAD

**Issue by davidngrc** [nicknsy/jellyscrub#111]
On 1.1.1.0

For example, folder structure like
\Film\TV\Game\EP01.mkv
\Film\TV\Game\EP02.mkv
\Film\TV\Game\EP03.mkv

now JellyScrub will create 
\Film\TV\Game\trickplay\EP01.bif
\Film\TV\Game\trickplay\EP02.bif
\Film\TV\Game\trickplay\EP03.bif

but in the Jellyfin Front End UI
it will show 
TV -> Game
Season 1 folder
and 
trickplay folder

Solution:
add a ".ignore" empty file in all the trickplay folder
eg:
\Film\TV\Game\trickplay\\.ignore

I tested it, and it work.
Ref:
https://www.reddit.com/r/jellyfin/comments/ama9ss/is_it_possible_to_have_jelly_fin_not_add_certain/

**Comment by nicknsy** [comment]
.ignore files already get added to trickplay folders. Are they not appearing when there are no season folders or are there no .ignore files in your other trickplay folders too?

**Comment by davidngrc** [comment]
.ignore file not in my trickplay folders.
suggest when JellyScrub doing re-scan, check this empty .ignore file exist, if not, create it.

**Comment by nicknsy** [comment]
Are these all newly generated trickplay files or were these made on an older version?

**Comment by davidngrc** [comment]
just check, they were create on oct 2022, so I guess they were created by old version.

**Comment by nicknsy** [comment]
Sorry for the late response. If they are old then simply manually creating a .ignore file should fix the issue. All future generations will have one automatically.
