### ISSUE TITLE
Generating bif files task not progressing and stuck at 0%

### ISSUE THREAD

**Issue by MakD** [nicknsy/jellyscrub#115]
The initial generate bif files has been stuck at 0% for more than a couple of hours now no progress made.

Operating System - Windows 10
Installation - Windows Installer
![jellyscrub](https://github.com/nicknsy/jellyscrub/assets/8217200/88b3ae52-82ea-4cb0-951d-dc00995e5394)

**Comment by nicknsy** [comment]
How big is your library and what sort of hardware are you running it on? It's a pretty intensive process and can take some time. If you check the jellyfin logs do you see messages about starting / successfully creating trickplay files?

**Comment by Catsrules** [comment]
I have seen the progress get suck before, my fix was restarting the Jellyfin server and then running the task again..  

As was suggested check to logs so you can get an idea what it is doing.

**Comment by MakD** [comment]
Sorry closing this issue. Took forever, but finally they were generated, and consecutive tasks are happening as intended.

**Comment by Y0ngg4n** [comment]
yeah seems like it is working for me too now. But takes really forever.
