### ISSUE TITLE
Jellyscrub for Truecharts

### ISSUE THREAD

**Issue by t-Val1** [nicknsy/jellyscrub#116]
I installed Jellyfin through the Truecharts Catalog on Truenas Scale. While I can create BIF files, I don't get a preview in any way, not in the web app (even with modified index.html) nor in any app. 

Does anyone have Jellyscrub working within Truenas?

**Comment by duplexsystem** [comment]
I am having the same issue

**Comment by nicknsy** [comment]
Could you please paste the parts of your jellyfin logs relating to jellyscrub and script injection status?

**Comment by duplexsystem** [comment]
I fixed the issue today, I had to clear the cache of my web browser

**Comment by t-Val1** [comment]
I fixed mine too, set the values of "runasUser" and "runasgroup" to 0 (run as root). Did the same for the Share Jellyfin accessed (set group and user 0 to have full access)
