### ISSUE TITLE
Not working in web

### ISSUE THREAD

**Issue by T0biasCZe** [nicknsy/jellyscrub#118]
I installed the plugin and added the script tag manually into the index.html
The plugin generates the .bif files, but it doesnt show them in web
In log it throws these 2 things related to jellyscrub
![image](https://github.com/nicknsy/jellyscrub/assets/44525446/c3fd31af-824a-42f7-afa7-72939ba75589)
![image](https://github.com/nicknsy/jellyscrub/assets/44525446/2543d103-097f-4ed2-9a16-4d52b6a056b1)
this the index.html: 
![image](https://github.com/nicknsy/jellyscrub/assets/44525446/6b8ccb35-a14d-4d90-8bfe-5464694c554a)
jellyscrub config:
![image](https://github.com/nicknsy/jellyscrub/assets/44525446/45c821b8-b497-4e09-940f-70ae51f2e183)

also, i am running jellyfin 10.9.0 in docker

**Comment by nicknsy** [comment]
Please use a stable release of jellyfin (10.8.x) for plugin support.

**Comment by T0biasCZe** [comment]
downgraded jellyfin to 10.8 still doesnt work in web
![image](https://github.com/nicknsy/jellyscrub/assets/44525446/681d3184-19f7-496e-a698-453dfbe0f9a0)

**Comment by nicknsy** [comment]
If you are not running Jellyfin in docker, try running `sudo chown -R jellyfin:jellyfin /usr/share/jellyfin/web/`, then restart Jellyfin and see if the error stops.

**Comment by MulverineX** [comment]
> If you are not running Jellyfin in docker, try running `sudo chown -R jellyfin:jellyfin /usr/share/jellyfin/web/`, then restart Jellyfin and see if the error stops.

Doing this fixed the problem for me. Thank you!!

**Comment by iluvatyr** [comment]
> If you are not running Jellyfin in docker, try running `sudo chown -R jellyfin:jellyfin /usr/share/jellyfin/web/`, then restart Jellyfin and see if the error stops.

Is doing this a security risk in any way?

**Comment by T0biasCZe** [comment]
it suddenly started showing the previews

**Comment by dandud100** [comment]
> > If you are not running Jellyfin in docker, try running `sudo chown -R jellyfin:jellyfin /usr/share/jellyfin/web/`, then restart Jellyfin and see if the error stops.
> 
> Is doing this a security risk in any way?

i am wondering too... @nicknsy ?
