### ISSUE TITLE
widescreen image format

### ISSUE THREAD

**Issue by SablyTv** [nicknsy/jellyscrub#120]
So I have a widescreen monitor and I'm guessing that Jellyscrub tries to only allow format 16:9, so my images get stretched out like below.

What I get:
![image](https://github.com/nicknsy/jellyscrub/assets/44623142/86c22b29-9fe7-4783-b5dd-c4adedf26cb6)

What I should get:
![image](https://github.com/nicknsy/jellyscrub/assets/44623142/15570a96-b98d-494f-b476-f56cce5c3514)

Note this only happens when I enter fullscreen, or when the browser is maximized. Work great in windowed mode. Could I fix this somehow?

**Comment by nicknsy** [comment]
I think it should be easy to fix by making the max size of the preview no greater than the size of the image. What's your monitor resolution just so I can test?

**Comment by SablyTv** [comment]
> I think it should be easy to fix by making the max size of the preview no greater than the size of the image. What's your monitor resolution just so I can test?

That's what I thought we could do. My screen res is 3440x1440
Lmk how it goes!

**Comment by SablyTv** [comment]
Hey just wanted to check if you found anything?

**Comment by nicknsy** [comment]
> Hey just wanted to check if you found anything?

Sorry have been pretty busy. I tried checking this out using the Chrome dev tools that let you test different resolutions, so it might not be 100% true to what you're seeing, but it didn't seem as disproportionately scaled like in the example you showed.

I see something else is styling the thumbnail images--if you remove/comment out the custom CSS you have set in the jellyfin settings do you get the same result?
