### ISSUE TITLE
Failed to load resource: the server responded with a status of 503 (Service Unavailable)

### ISSUE THREAD

**Issue by piotrek2555** [nicknsy/jellyscrub#123]
"Failed to load resource: the server responded with a status of 503 (Service Unavailable)" in console brave   ,   script was  add to html index.html in jellyfin

ClientScript:436     GET http://192.168.2.10:8096/Trickplay/2d168004a5eccd256f37ab8bfb761043/GetManifest 503 (Service Unavailable)

1.58.124 brave 

SERVER hp prodesk 600g3 mini i5-6500t 16gb ram , jellyfin install on debian 12 directly

**Comment by nicknsy** [comment]
This is intended behavior to let the client know that the manifest is unavailable currenty but to keep trying as it will be available later (in the case of on-demand generation).
