### ISSUE TITLE
HDR content is not tone mapped

### ISSUE THREAD

**Issue by harsh0596** [nicknsy/jellyscrub#129]
![image](https://github.com/nicknsy/jellyscrub/assets/11883323/e4c33739-da62-48dc-86c5-a8171d3f9161)

**Comment by ERivierePEReN** [comment]
I believe you can go in the plugin's settings to activate tone mapping

**Comment by nicknsy** [comment]
If you have HW tonemapping enabled in jellyfin, enabling HW acceleration for trickplay generation will also enable tonemapping of the outputted images.
