### ISSUE TITLE
Support for jellyfin > 10.9.0?

### ISSUE THREAD

**Issue by hoonlight** [nicknsy/jellyscrub#131]
Hi,

I was wondering if you have any plans to support jellyfin 10.9.0 and above?
I know it's still an unstable build, but I was wondering if you have any plans to support it in the near future.
Thanks for a great plugin.

**Comment by nicknsy** [comment]
Hi,

There aren't currently plans to support 10.9.0 since trickplay support has already been upstreamed in https://github.com/jellyfin/jellyfin/pull/9554.

**Comment by ERivierePEReN** [comment]
@nicknsy 
Do you know if .bif files generated using Jellyscrub will be compatible with Jellyfin's implementation?

**Comment by nicknsy** [comment]
> @nicknsy 
> 
> Do you know if .bif files generated using Jellyscrub will be compatible with Jellyfin's implementation?

It wont be since the core team wanted a different implementation for trickplay. I'm planning on creating a conversion tool though.

**Comment by ERivierePEReN** [comment]
> > @nicknsy
> > Do you know if .bif files generated using Jellyscrub will be compatible with Jellyfin's implementation?
> 
> It wont be since the core team wanted a different implementation for trickplay. I'm planning on creating a conversion tool though.

My NAS' weak CPU cores thank you for your everything!

**Comment by Pfuenzle** [comment]
Hi,
are there any news on the conversion tool? Thanks :)

**Comment by nicknsy** [comment]
> Hi,
> 
> are there any news on the conversion tool? Thanks :)

The convert version is already released to users who update to 10.9.0. Check out the main page of the github for more info or you can post here with any questions

**Comment by Pfuenzle** [comment]
Oh I'm sorry, I went straight to the issues to search for it since I remembered it being mentioned there, didnt even think of checking the readme 😅.
Thanks a lot for the info and your work in general :)
