### ISSUE TITLE
Possible to pause preview generation without disabling current previews functionality?

### ISSUE THREAD

**Issue by hianick** [nicknsy/jellyscrub#136]
I've already generated previews for my current media library, but now I would like to add a very large amount of home videos that don't require previews. I don't see any option to pause generation. Is there maybe a config toggle somewhere I'm unaware of?

**Comment by nicknsy** [comment]
Sorry, there's no way to disable preview generation per library in jellyscrub. However, that has been implemented in the new trickplay feature that will be part of jellyfin's next major release.
