### ISSUE TITLE
[Question] How to only create trickplay to specific category

### ISSUE THREAD

**Issue by chienhao10** [nicknsy/jellyscrub#140]
I have enabled 'Generate trickplay files on demand when a client requests one', and i thought i am able to choose which folder(category) to enable this (or alteast when i am watching a media when that is enabled). Since there will be lots of existing media and now it has been 2 days non stop running creatingg trickplay, i only want my "Movie" category can enable this plugin, is there anyway to do so?

**Comment by nicknsy** [comment]
There is no way to do this in jellyscrub however this feature has been added to the native trickplay implementation which will be available in 10.9.0
