### ISSUE TITLE
[Question] Does Jellyscrub keep track of already generated files?

### ISSUE THREAD

**Issue by Optimus1008** [nicknsy/jellyscrub#141]
Hi,
I have a feeling that the scheduled tasks may lead to already generated files being replaced.
My library is pretty large and the resolution of generated images is fairly high, so I'm not sure if the process maybe just takes a very long time (multiple days at this point).
So, does Jellyscrub keep track of already generated files to avoid duplicated processing?
If yes, how does it determine, which files can be skipped (i.e. using a hash to detect changes or just file names)?
Many thanks in advance!

**Comment by nicknsy** [comment]
The plugin checks if a trickplay file corresponding to associated media file exists, so they should not be regenerating unless you are changing the names of the files after they've been added to your library.

You can check the log and see whats being generated too if you're interested.

**Comment by Optimus1008** [comment]
Ah, thank you for the quick response! Will have to keep in mind in case I wanna use Tdarr in the future.
