### ISSUE TITLE
Cannot create BIF Files

### ISSUE THREAD

**Issue by ageisen2000** [nicknsy/jellyscrub#142]
I'm not 100% sure what is happening here. I looked at the code and I shouldn't have any null references, I can debug if shown how.

I'm using the linuxserver.io docker container.

```
jellyfin  | [03:17:55] [ERR] [13] Nick.Plugin.Jellyscrub.Drawing.VideoProcessor: Error while creating BIF file
jellyfin  | System.NullReferenceException: Object reference not set to an instance of an object.
jellyfin  |    at Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder.GetOutputCodec(String hwaccelType)
jellyfin  |    at Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder.ExtractVideoImagesOnInterval(String inputFile, String container, MediaStream videoStream, MediaSourceInfo mediaSource, Nullable`1 threedFormat, TimeSpan interval, String targetDirectory, String filenamePrefix, Int32 maxWidth, CancellationToken cancellationToken)
jellyfin  |    at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.CreateBif(String path, Int32 width, Int32 interval, BaseItem item, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
jellyfin  |    at Nick.Plugin.Jellyscrub.Drawing.VideoProcessor.Run(BaseItem item, MediaSourceInfo mediaSource, Int32 width, Int32 interval, CancellationToken cancellationToken)
```

My settings:
![image](https://github.com/nicknsy/jellyscrub/assets/8844888/5f0f5827-aa20-4082-bb96-efe763d126ae)

Nvidia-SMI output (from inside the container) in case you need my driver version
![image](https://github.com/nicknsy/jellyscrub/assets/8844888/0f39a9f7-710d-4bac-8f9a-10125fff8f7f)

**Comment by ageisen2000** [comment]
Welp -- I figured it out. I had to set up NVENC encoding on jellyfin for transcodes as well. Then it all started working.

IDK if I missed something in the documentation. 

Can you add a message or a check in the addon settings to tell people to enable NVENC?

**Comment by nicknsy** [comment]
> Welp -- I figured it out. I had to set up NVENC encoding on jellyfin for transcodes as well. Then it all started working.
> 
> IDK if I missed something in the documentation.
> 
> Can you add a message or a check in the addon settings to tell people to enable NVENC?

Glad you were able to figure it out! The "Uses same options as set in "Playback"  to HW accelerate" was intended to let people know that they need transcoding enabled in jellyfin as a whole, but admittedly there is a lot of text there and I can see how that would be unclear.
