### ISSUE TITLE
Changing image interval

### ISSUE THREAD

**Issue by ZanderPittari** [nicknsy/jellyscrub#147]
I just realised my image interval was 10000ms and that is too long for this amazing plugin to be useful, just wondering if I change it to a lower interval time, say 1000ms, will jellyscrub automatically go and regenerate newer .bif files?

I changed it and ran the bif generator task on jellyfin but no luck.

**Comment by nicknsy** [comment]
Bif files contain their interval as part of the file, so changing the interval in the plugin configuration only changes how newly generated files will behave. If you would like, you can delete all your old files using a command like this https://github.com/nicknsy/jellyscrub/issues/138, however I believe 10,000ms (10s) is the default interval which is generally enough for most media that is 30m+.

In 10.9.0 are able to use the "Replace existing images" option during a metadata refresh to generate new trickplay images, however 10.9.0 is still in beta at the moment.
