### ISSUE TITLE
Unable to convert .bif files when saved on the same path of the main file itself

### ISSUE THREAD

**Issue by RodoMa92** [nicknsy/jellyscrub#149]
It doesn't seem to picking up .bif files saved in <main_file_location>/trickplay/<main_file_name>.bif. Is this properly handled?

**Comment by RodoMa92** [comment]
Resolved. I had to wipe the configuration for bootup problems and it needed the setting enabled in the options of the old version. Now it works properly.

**Comment by sakuyamaij** [comment]
Same. How do you fix it

**Comment by nicknsy** [comment]
> Same. How do you fix it

The conversion process uses the same configuration settings that were set before updating Jellyscrub to 2.0. This means whatever option you used for generating the trickplay files originally is what is used for conversion. If the configuration file was deleted or modified incorrectly before updating you would have to go into the jellyfin plugin folder and edit the Jellyscrub config option "LocalMediaFolderSaving" manually.

**Comment by RodoMa92** [comment]
> > Same. How do you fix it
> 
> The conversion process uses the same configuration settings that were set before updating Jellyscrub to 2.0. This means whatever option you used for generating the trickplay files originally is what is used for conversion. If the configuration file was deleted or modified incorrectly before updating you would have to go into the jellyfin plugin folder and edit the Jellyscrub config option "LocalMediaFolderSaving" manually.

Which is what I did to fix this issue, manually changing settings in the configuration file. After that it worked 100% fine.
