### ISSUE TITLE
Cannot be uninstalled

### ISSUE THREAD

**Issue by thepwrtank18** [nicknsy/jellyscrub#150]
When uninstalling Jellyscrub and restarting Jellyfin, the older version of Jellyscrub just puts it back. This makes it impossible to uninstall it.

**Comment by nicknsy** [comment]
There is no functionality in the plugin that would add itself back, so this is likely an issue with jellyfin. However, if removing the repo and uninstalling does not work, you can manually remove the plugin files from the jellyfin config folder.

**Comment by travisterrell** [comment]
If helpful to future people, I found that this happens if you don't remove the repository before rebooting. (Was crazy frustrating to figure out, haha. But it *is* mentioned in the uninstall instructions.)
