### ISSUE TITLE
Remove Scheduled Tasks

### ISSUE THREAD

**Issue by holocronology** [nicknsy/jellyscrub#151]
I don't think this was addressed in your migrate to native trickplay, it looks like one also needs to delete the "Generate BIF Files" scheduled task. Yes?

![image](https://github.com/nicknsy/jellyscrub/assets/65265114/f2c32ae7-2f5c-4ab6-af78-63b788941754)

**Comment by nicknsy** [comment]
Maybe try clearing your browser cache/cookies for the site. I don't see how the scheduled task could remain as it is apart of the plugin code.

**Comment by c1em3ntchua** [comment]
Having the same issue too even after clearing cache and cookies. Happens on both Chrome and Edge. Haven't tested other browsers.

**Comment by nicknsy** [comment]
In both cases, when the scheduled task still shows does the plugin also still show up under installed plugins? Can you access its configuration page?

> Having the same issue too even after clearing cache and cookies. Happens on both Chrome and Edge. Haven't tested other browsers.

Had you ever logged in on Edge before or did you do it specifically just to test?

**Comment by c1em3ntchua** [comment]
Somehow the plugin reappeared in 'My Plugin' page even though I was very sure I had uninstalled it per the instructions. Proceeded to uninstall it (once again), rebooted Jellyfin server, and it's gone now.
