### ISSUE TITLE
Unable to start conversion on jellyfin 10.10.0

### ISSUE THREAD

**Issue by huige830** [nicknsy/jellyscrub#154]
It worked with 10.9.0 but when I upgraded to 10.10.0 it didn't work.  Jellyscrub 2.0.0.0
The following is the log

[19:05:08] [ERR] [25] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Trickplay/Convert/ConvertAll.
System.MissingMethodException: Method not found: 'Jellyfin.Data.Entities.TrickplayInfo MediaBrowser.Controller.Trickplay.ITrickplayManager.CreateTiles(System.Collections.Generic.List`1<System.String>, Int32, MediaBrowser.Model.Configuration.TrickplayOptions, System.String)'.
![20241110_191449](https://github.com/user-attachments/assets/76fde456-5de9-479e-8694-712b455c66b7)

**Comment by nicknsy** [comment]
10.10.0 had API-breaking changes, so I've released a new version that should fix this issue. Please make a new post if you run into any other issues. However, if you already used this to convert your .bif files in 10.9.0 you shouldn't need to have Jellyscrub installed anymore.
