### ISSUE TITLE
Jellyscrub doesn't respect file location and prefers old location.

### ISSUE THREAD

**Issue by SandyRodgers-2017** [nicknsy/jellyscrub#20]
Hi, 
Thanks for the Plugin. However I am having a problem. The problem is that JellyScrub is not respecting the new location of my files and is still using the old  location to store .bif files unless I delete that directory. I rsync my files so the old location has a nearly identical directory structure, but if I delete a directory then Jellyscrub defaults back to the new and correct location. When I originally setup my Jellyfin Media Directory I had set it up in one location. However, later on I changed it when it became better to put in on my home directory. Jellyscrub doesn't seem to respect this change and wants to save the files at the old location. This only seems to happen when I use the scheduled task not when I watch the videos one by one. I'm wondering how does Jellyscrub know what directory to save files into and if I could change that value or even if you could a the ability to tell Jellyscrub where to point in order to read files.

**Comment by nicknsy** [comment]
Hmm all the times bif files are generated or retrieved it uses the item object directly passed in by jellyfin. If this is happening then it sounds like an issue with jellyfin itself as jellyscrub never saves the location of .bif files.

Not sure if anything can be done to solve this except a restart or rescan

**Comment by nicknsy** [comment]
Closing this for now since there doesn't seem to be any updates about this
