### ISSUE TITLE
[Bug] "trickplay" season introduced in JF library - only for some shows

### ISSUE THREAD

**Issue by LeviSnoot** [nicknsy/jellyscrub#21]
![image](https://user-images.githubusercontent.com/13402525/182995703-581970fd-db54-41a8-b3f9-794438e1d3b0.png)

This only appears in a couple of the shows in my library. I'm not sure if there's a weird syntax reason for this but I'll list them below in case it helps. 

"Save trickplay files within media folders" is enabled.

Shows where trickplay season appears:

- American Dragon: Jake Long
- Hunter x Hunter
- What We Do in the Shadows

**Comment by nicknsy** [comment]
Looks like jellyfin is using the folder as a season even though there are no video files. Is there any way to manually block a folder from appearing as media. If its only some shows I dont know why it would inconsistently be doing it either. 

Maybe if it was a hidden folder with a . like someone suggested before it wouldn’t happen but Im really not sure how jellyfin decides what to look for

**Comment by LeviSnoot** [comment]
Never mind this one, I found that the affected shows are in a flat folder structure and not season folders like they're supposed to be. So in a normal folder structure it would look like `Series Name/Season 1/trickplay`, but in this case it's just `Series Name/trickplay`. Easily fixed on my end, although it does bring up the idea of making the trickplay folder hidden to avoid this happening to other people. Thanks anyway!
