### ISSUE TITLE
[Feature Request] Use pools argument in ffmpeg command

### ISSUE THREAD

**Issue by SandyRodgers-2017** [nicknsy/jellyscrub#23]
Hi,
Multi Core Processing doesn't seem to work correctly when it comes to encoding bifs. It still uses 70 to 100 percent of my cpu when encoding even when I set threads to 1. My cpu is an i7700, which is 4 core and 8 threads. Could you add the pools command to your ffmpeg config. In this link: https://trac.ffmpeg.org/ticket/3730. There is talk about using the pools argument to help limit the amount of cpu usage. I'm not sure if it is applicable to this situation, since they are talking about libx265 encoding, but I hope so.

**Comment by nicknsy** [comment]
I looked into it and the threads option wasn't working properly because it was only applying to the creation of images and not the decoding of the video. As such, I won't be adding the pools option but threads option should start working in v1.1
