### ISSUE TITLE
Bug: BIF exists, injection loaded, but Web UI not shown

### ISSUE THREAD

**Issue by davidngrc** [nicknsy/jellyscrub#25]
I see BIF is successfully created, and below are their logs.
and the injection script is also show successfully injected in the logs, and in web source code, I also see trickplay script is there.

in the firefox, I press F2, go to console, nothing mention trickplay or 
however, I got below error, since I have many plugin, not sure if it is related.
The script from “http://x.x.x.x:8096/jellyfin/web/index.html” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
[index.html](http://x.x.x.x:8096/jellyfin/web/index.html#!/video)
Uncaught SyntaxError: expected expression, got '<'

the actual filename:
For.Your.Eyes.Only.1981.BluRay.1080p.x265.10bit.3Audio.MNHD-FRDS.mkv

[INF] Finished creation of trickplay file "/Film/Movie_Collection/007 Collections/007系列之12最高机密.For.Your.Eyes.Only.1981.BluRay.1080p.x265.10bit.3Audio.MNHD-FRDS/trickplay/For.Your.Eyes.Only.1981.BluRay.1080p.x265.10bit.3Audio.MNHD-FRDS-320.bif"

the actual filename:
Game.of.Thrones.S02E01.The.North.Remembers.720p.10bit.BluRay.2CH.x265.HEVC-PSA.mkv

[INF] Finished creation of trickplay file "/Film/TV/Game of Thrones (2011)/Game.of.Thrones.SEASON.02.S02.COMPLETE.720p.10bit.BluRay.2CH.x265.HEVC-PSA/trickplay/Game.of.Thrones.S02E01.The.North.Remembers.720p.10bit.BluRay.2CH.x265.HEVC-PSA-320.bif"

**Comment by nicknsy** [comment]
Did you clear the cache, cookies, and local storage in Firefox for the jellyfin website?

**Comment by davidngrc** [comment]
yes, I have clear it.
and I also try install a new browser, chromium just now. and still don't see bif appear in the web ui when playing the video.
in the jellyfin log, I see no mention of keyword ( trickplay / injection / bif / jellyscrub ) when or after I play the video that has bif.

note, the whole media folder and all its sub folder or files (include bif, as I store them in the same video folder) have been chmod 777
the /usr/share/jellyfin/web/index.html also in chmod 777

My desktop web browser is in ubuntu 22.04 desktop, firefox and chromium are in latest.
Jellyfin is in Proxmox 7.02 LXC (ubuntu 22.04 server)
Jellyfin is in 10.8.3 (the media info was restore by copying the old file from old server /var/lib/jellyfin/ )

**Comment by nicknsy** [comment]
Do you have a base url set in jellyfin? If so, see here https://github.com/nicknsy/jellyscrub/issues/14

If not, please post your full index.html and jellyfin logs (redacting anything if its sensitive)

**Comment by davidngrc** [comment]
yes I did.
the base url is /jellyfin

**Comment by nicknsy** [comment]
If you've set the base url follow #14 for a fix until one is officially released
