### ISSUE TITLE
BIF Creation Scheduled Task Freezes

### ISSUE THREAD

**Issue by gottsman** [nicknsy/jellyscrub#26]
The scheduled task has been at 6.2% for about 8 hours on a large 16 core machine (new install). Restarting the task doesn't fix the issue. My logs are fairly long. Can I enable debugging within the plugin? My logs are fairly terse, but I don't see anything for this task.

**Comment by nicknsy** [comment]
You should see something like “starting trickplay generation for —— at width —-“ when it starts, then “finished generating…” when it finishes. Do you see any of those messages? You might be able to grep/search Jellyscrub in the logs

**Comment by gottsman** [comment]
I did some more reading and the jobs are completing successfully, just slowly. I think my specific slowness was related to multiple consecutive 4K movies. I think my slowness would be helped if HW acceleration could be implemented as requested in #12.
