### ISSUE TITLE
[Bug] Previews not working when it jumps to next episode

### ISSUE THREAD

**Issue by Fallenbagel** [nicknsy/jellyscrub#28]
The previews work perfectly when i explicitly open a specific episode and the previews are shown for that exact same episode but when it finishes playing and jumps to next episode, previews does not appear.

For example, here I opened an item S01E02 (works):
![image](https://user-images.githubusercontent.com/98979876/184524242-b577f78e-d97d-4cd5-a03b-9d64c9a9b74b.png)

But when I open S01E01 and then jump to/let it finish playing and start the next episode (does not work):
![image](https://user-images.githubusercontent.com/98979876/184524269-21c84fb2-b9de-4477-9e1d-42e7fc330b66.png)

(Occurs on both web client as well as jmp)

**Comment by Fallenbagel** [comment]
From my testings, I found that GetBif is not called in subsequent episodes:
S01E01 (opened directly so it got called):
![image](https://user-images.githubusercontent.com/98979876/184524978-9e0d4d5b-8164-473b-b178-f29479a65d1a.png)

S01E02 (after jumping from S01E02 so not directly opened):
![image](https://user-images.githubusercontent.com/98979876/184524998-ca71e6db-a161-41b9-a4a2-0560b3ab2127.png)

As you can see from this, GetBif is not called on the subsequent episode when jumped. Gets called when directly opened though 

https://user-images.githubusercontent.com/98979876/184525276-069b1d79-2690-466e-bcad-bc31b78ee413.mp4

**Comment by nicknsy** [comment]
Yeah Ill try to fix this soon. Looking to rewrite a good bit of the client script

**Comment by nicknsy** [comment]
Fixed by https://github.com/nicknsy/jellyscrub/commit/c5720a285e1d08ccfef4b80886976948b10f8d9c

**Comment by nicknsy** [comment]
Fixed by https://github.com/nicknsy/jellyscrub/commit/f69f784889063ce5b3ea7d1e5ce674e8af32ed23
