### ISSUE TITLE
Show timestamp instead of percentage of scrobble images are not created yet

### ISSUE THREAD

**Issue by Pfuenzle** [nicknsy/jellyscrub#31]
When the scrobble images have not been generated and a user hovers over the timeline, instead of the time the percentage of the progress is shown.

This is IMO not really helpful to the user, Is this intended or would you be willing to change it?
Thanks a lot :)

![grafik](https://user-images.githubusercontent.com/11798845/184875406-f19d41d1-22a4-4d3a-89ea-adf02274cc0c.png)

**Comment by nicknsy** [comment]
Is this a TV show? If so, it may be related to #28. It's supposed to keep default functionality if there are no trickplay files, and I'm pretty sure it worked before on movies but I'm not 100%.

**Comment by Fallenbagel** [comment]
I can confirm that trickplay not generated files have the default functionality intact on both tv shows and movies. This happens when trickplay files have been generated but is GetBif is not being called

**Comment by nicknsy** [comment]
Fixed by https://github.com/nicknsy/jellyscrub/commit/f69f784889063ce5b3ea7d1e5ce674e8af32ed23
