### ISSUE TITLE
Process Priority

### ISSUE THREAD

**Issue by Froghut** [nicknsy/jellyscrub#39]
Not sure if I'm the only one with this scenario, but I would like to run ffmpeg with the maximum amount of threads but very low process priority, that way it can use as much CPU as possible - as long as there are no other more important processes running. With only thready I can limit it to use i.e. 50%, but that will potentially slow down other processes or run not as fast as possible while there are no other processes running. Or am I missing something when using the threads option?

**Comment by nicknsy** [comment]
Ah I see. I guess I just misunderstood the usage of process priority. I'll add that option back but not sure when Ill get around to the next update

**Comment by Froghut** [comment]
That's no problem, thanks for that!
