### ISSUE TITLE
Web UI not working - uncaught type error?

### ISSUE THREAD

**Issue by christovic** [nicknsy/jellyscrub#41]
Manually injected the script as I didn't want index.html to be writable by my jellyfin user, the js is loaded correctly, but I'm getting this message: 

`ClientScript:68 Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at ClientScript:68:19`

No previews are popping up on the videos that have confirmed .bif files generated. I'm not sure if the above message is fatal, so not sure where to look basically.

**Comment by nicknsy** [comment]
What browser + version and are you running the stock latest of https://github.com/jellyfin/jellyfin-web? Could you paste the contents of the index.html as well.

**Comment by christovic** [comment]
So sorry, just realised I was putting the script tag before the body as I'm used to. It's working great now that I've moved it to the right place, so sorry to bother you! Great plugin, thanks so much for it!
