### ISSUE TITLE
[Question] Does this work behind a reverse proxy and on TV clients?

### ISSUE THREAD

**Issue by simkin** [nicknsy/jellyscrub#48]
Hopefully somebody is able to answer my three questions:

1. Will this work when hosting Jellyfin behind an Nginx reverse proxy?
2. Will this work with the Android TV and/or WebOs clients as well?
3. Why is the script loaded before `</body>` instead of `</head>`?

**Comment by nicknsy** [comment]
This works behind a nginx reverse proxy as long as everything is setup properly. 

I'm not sure if it works with TV clients, but it did work with the android phone client last I checked. I know for sure that it no longer works with roku though.

The script is loaded after body so it loads after the DOM elements it manipulates. I recently made some updates to the trickplay code that may make it irrelevant when it loads but for now its easier to keep it at the end of body.
