### ISSUE TITLE
[Question] How do I activate it on Jellyfin Windows version?

### ISSUE THREAD

**Issue by kimpig** [nicknsy/jellyscrub#51]
I installed Jellyfin in the Windows installer version. After installing this plugin in the repository, I created the BIF file in the media folder, but it does not work. Do I need to manually put the script in the jellyfin-web folder to work? Also, is the way I put the script correct?

![image](https://user-images.githubusercontent.com/61234733/202901748-f74c43a4-ca0f-43a5-bc35-8524758df1b3.png)

I'm sorry for the rudimentary question.

**Comment by nicknsy** [comment]
- Could you post the startup logs of jellyfin?
- When you say you created the BIF file, was that through the scheduled task or on-demand creation? Can you verify that the file is in the media folder with the other videos?
- After installation of the plugin, did you clear your website cache for your jellyfin website on your browser?

Looks like the script line is in the correct location

**Comment by nicknsy** [comment]
Hmm not sure if using the intro skipper web at the same time would cause issues, but I wouldn't think so. 

Can you open developer tools in your browser, go to "Console" and refresh the jellyfin page and see if there are any errors on load. Also if you click on a video it should make mention of whether a BIF file was found in the console. Could you screenshot and upload an image of what the console says?

Also, if you want to manually make sure the trickplay script endpoint works try going to http://{your jellyfin}/Trickplay/ClientScript and making sure it returns the script. 

Also, did you manually put the line in the index.html or did the plugin inject it?

**Comment by nicknsy** [comment]
Yes, it uses ffmpeg to extract frames from the videos. It can take quite a while to finish depending on the cpu you have in the system.

As for whether or not to save to the media folder, it's up to you. I think saving to the media folder makes them easier to manage/move in the future. However, once you turn it on I wouldn't turn it off as it would require regenerating all BIF files in a new location.

**Comment by kimpig** [comment]
When saved to the media folder, Jellyfin seems to recognize the trickplay folder as a season.  Can't I solve this?

**Comment by nicknsy** [comment]
What is your folder structure for television? I've heard if you don't create subfolders for each season it will do this. Is your folder structure like this?

- Show Name/
   - Season 1/
     - Ep Name 001.mkv
     - Ep Name 002.mkv
   - Season 2/
     - Ep Name 001.mkv
     - Ep Name 002.mkv

**Comment by kimpig** [comment]
Oh, I got it. However, adding .ignore files one by one is too much work. I hope the file will be automatically created soon.
