### ISSUE TITLE
Getting empty space below the vanilla one

### ISSUE THREAD

**Issue by parasiteoflife** [nicknsy/jellyscrub#55]
I'm using JF 10.8.8. This is what I'm getting after playing a movie (I haven't scanned anything, I'm trying the at-request creation of the thumbnails):

![firefox_2022-12-03_06-08-16](https://user-images.githubusercontent.com/57022988/205437945-8afb96f2-f490-4104-a293-cab7049215d5.png)

**Comment by nicknsy** [comment]
Are you using any custom themes/styling?

**Comment by parasiteoflife** [comment]
Aaah, damn, yes, I forgot about it, it must be it. Thanks.
