### ISSUE TITLE
Script is loading but GetManifest does not work

### ISSUE THREAD

**Issue by JPVenson** [nicknsy/jellyscrub#57]
Hey,

Awesome idea thanks for your work.
But I have some problems right now, i have installed the plugin and did not yet started a full scan as the scheduled task but enabled the on demand generation. According to the Dev console, `/Trickplay/1471dbcac6cf566c17ef5a2c869e052e/320/GetBIF` endpoint is called and returns something, however it is not displayed anywhere.

**Comment by nicknsy** [comment]
Any errors in Javascript console? How big is the BIF file getting returned? Are you using any sort of custom jellyfin frontend (e.g. jellyfin-vue) that would cause the script to be unable to find the correct elements?

**Comment by JPVenson** [comment]
No none, dev console says around 7mb for a episode of stargate. Stock Jellyfin web UI, fresh out of the docker container.

**Comment by nicknsy** [comment]
It should work with any client that's just a web view and not it's own native client. It worked on ios and android phones at one point but I don't think it works with AndroidTV since I think that's its own native client.
