### ISSUE TITLE
Editing of index.html will fail if Jellyfin is installed from a Linux package

### ISSUE THREAD

**Issue by kpfleming** [nicknsy/jellyscrub#6]
The README currently notes that this problem may occur with Docker containers, but it will also happen if Jellyfin is installed from any of the Linux packages (for Arch, Fedora, CentOS, Debian, and Ubuntu). In those cases the daemons run as user `jellyfin` but all of the web files are owned by `root`.

In addition, if the user edits the file to include the jellyscrub script, that will be overwritten if the package is updated, and then of course the automatic insertion will once again fail :-)

I'm happy to try to write some language for README which covers this, if that would be helpful.

**Comment by nicknsy** [comment]
Thanks, I've added some additional info to the readme that should cover this 👍
