### ISSUE TITLE
not working with android/android TV

### ISSUE THREAD

**Issue by gaming09** [nicknsy/jellyscrub#61]
i have confirmed this work on web, but on android and android TV its not showing up, do any changes need to be made to the default install?

**Comment by gaming09** [comment]
edit: It looks like it works on LAN but when it hits my Reverse proxy it doesnt work - something with HAproxy (its not going outbound at that point due to split dns)

**Comment by nicknsy** [comment]
Jellyscrub cannot work on native clients like android tv, roku, etc that are not web-based.

**Comment by brianjmurrell** [comment]
Pity.  My primary (and pretty much only) client everywhere is Android TV (CCWGTV to be exact).
