### ISSUE TITLE
Weird injection issue in some browsers

### ISSUE THREAD

**Issue by Terrails** [nicknsy/jellyscrub#62]
I am currently using this plugin without any issues on my phone and via the desktop app, but have some odd issue on firefox. 
ClientScript is not injected until I do a force refresh via CTRL + F5 or CTRL + SHIFT + R. If I refresh the page by just using F5 or CTRL + R  or open a new tab with jellyfin the script is not injected again. I have tried clearing all website data and cookies but it did not change this behavior. This issue seems to also be present in Microsoft Edge. I haven't been able to reproduce it in Chrome.

**Comment by nicknsy** [comment]
Does the issue happen if you try in an incognito window?
