### ISSUE TITLE
Make the "trickplay" directory hidden

### ISSUE THREAD

**Issue by Chaphasilor** [nicknsy/jellyscrub#8]
Hi, I just noticed that the plugin generates a `trickplay` folder next to every video file it finds, when the setting "Store next to media files" is enabled. While this works well, I believe renaming that folder to `.trickplay` might be a good idea. This way it will either be hidden by default or always be at the top and don't interfere with sorting. The functionality would still be the same, but the semantics of this being *metadata* would be highlighted :)

What do you think?

**Comment by nicknsy** [comment]
For now this isn't planned to keep compatibility will all the trickplay files already generated under the "trickplay" folder. I don't want to introduce something yet that may break older versions or complicate the code more, but if there was enough interest in this then maybe.
