### ISSUE TITLE
Generate BIFs on another machine

### ISSUE THREAD

**Issue by digitalbarrito** [nicknsy/jellyscrub#81]
Is it at all possible to do the BIF generation on a separate machine? I run Jellyfin on my Pi CM4 and it's taken days just to get through 20% of my library, even with the new HW accel support. So I'm curious if I can use my PC with significantly better hardware to grunt through the BIF generation for my Pi, since I can access the drive the Pi uses and holds my library on my PC as well.

**Comment by nicknsy** [comment]
Yup just download the jellyfin server onto your main computer, point it to whatever media, install jellyscrub, and run the generation task with "Save to media folder" enabled. As long as you have "Save to media folder" enabled on your server as well it'll grab the same files.

Also, if you have a huge library I'd turn off metadata scraping so you don't have to download a bunch of useless data just to generate bifs.

**Comment by digitalbarrito** [comment]
> Yup just download the jellyfin server onto your main computer, point it to whatever media, install jellyscrub, and run the generation task with "Save to media folder" enabled. As long as you have "Save to media folder" enabled on your server as well it'll grab the same files.
> 
> Also, if you have a huge library I'd turn off metadata scraping so you don't have to download a bunch of useless data just to generate bifs.

Hey I appreciate the response! I was wondering if something like that would work. Doing that now and hoooo boy, it's going way faster on my main machine
