### ISSUE TITLE
Request - Multiple Image Intervals for Set Video Length Ranges

### ISSUE THREAD

**Issue by maru801** [nicknsy/jellyscrub#82]
It would be nice to be able to generate trickplay files at different image intervals depending on the source length.

I have mine generated at a 5 second interval which are reasonable for content around 20-30 minutes in length. But I find that this is a bit much for 1+ hour long movies where the progress bar gets squeezed in with more video position data and becomes harder to fine-scrub and see the 5 second changes. I would like to have these longer videos generated at the default 10 second interval.

Something like having a custom option to chose X image interval for X to X video length and Y image interval for Y to Y video length is what I'm thinking.

**Comment by nicknsy** [comment]
Related to #75

**Comment by maru801** [comment]
Closing this as Jellyscrub integrated with Jellyfin & is EOL.
