### ISSUE TITLE
Issue with the default width resolution auto-including itself despite not being used.

### ISSUE THREAD

**Issue by maru801** [nicknsy/jellyscrub#85]
Does the plugin change the configured resolutions at which BIF files are generated to include 320px after a while?
I set my files to only be generated at 400px. I also turned off all forms of scanning to generate the BIF files unless it's done through the plugin's scheduled task. I have the task set to run on a weekly basis so it will generate the files for any new video then.

Turns out that I noticed my server was using the cpu for something and I found out that it was Jellyscrub doing its thing. I didn't add any new videos, so I checked Jellyfin's logs and saw what was happening. Somehow, Jellyscrub started generating BIF files at the default 320px resolution. I went to the plugin's settings and found that in the width resolution box, it was set to "320,400". 

I have no idea how that happened since I specified only to use 400px. I'm also sure I didn't include 320 in there since I only added one number (400) and no others separated by a comma. I guessed that it was the scheduled task that included the 320px option, so I remade the scheduled task to run again, but nothing happened this time.

Edit: I set a schedule task again for this to run some hours later from before, and the same issue occurred. So I do think it has something to do with the scheduled task.

**Comment by Don-Chris** [comment]
I found the same bug, the setting is reset after restarting the jellyfin server.

**Comment by maru801** [comment]
Can confirm that was the cause of the issue. Looks like there is some code that includes 320px in there when the server is restarted.

Now, I just have to make sure to edit the resolution option after each server restart.
