### ISSUE TITLE
Jellyscrub takes far too much time on scheduled task

### ISSUE THREAD

**Issue by UltraHKR** [nicknsy/jellyscrub#89]
I have installed jellyscrub on Jellyfin

Docker container
Jellyfin v10.8.9 (linuxsever.io 10.8.9-1-ls201)
Jellyscrub v1.0.0.9

I followed the recommended settings
Ran manually a "Generate BIF files task) took a 5+ hours... (This is OK)

But I setup a daily task @ 3:00AM, but it takes the same 5 hours...
This makes my server fans spool into jet mode, for a long while... for 10 episodes (25 min aveage) or less
![image](https://user-images.githubusercontent.com/49404533/221233411-6fc610ec-dd63-496d-99ba-4a47ce1df6a3.png)

How can i help you diagnose this?

**Comment by maru801** [comment]
If you go into your logs, you can see what it was doing. If all your media had BIF files created in the first run, the daily task should only apply to new videos that don't have the BIF files.

In your Jellyfin dashboard, go to your logs and open the system log in a new browser. You can reload this log to see new system log updates. Go back to your daily task and manually run it again. Then go back to your log, reload it, and it will tell you what it's doing at the bottom of the log's page.

**Comment by nicknsy** [comment]
The task is set to only run for 5 hr, so once it reaches 5 hr run time it will exit. If you've got much media that can be processed in that timeframe each time you run the task it will max out at 5 hours.

This is part of the original forked code so I can look into if there's a way to uncap it.

**Comment by UltraHKR** [comment]
If understand you correctly, if my library is large enough that it doesn't finish in 5 hours it will keep using the same (5 hours) till the library is completely scanned?

Afterwards it should run far faster?
(only scanning new files...

**Comment by nicknsy** [comment]
Yes that's right
