### ISSUE TITLE
kofi for nicknsy/jellyscrub team

### ISSUE THREAD

**Issue by craigers521** [nicknsy/jellyscrub#90]
I love this feature so much and i use it constantly.  I need a better way to thank you. Get a kofi so i can better convey my gratitude :)

**Comment by nicknsy** [comment]
Hey, I appreciate that you like the plugin! I've signed up for github sponsors so I believe there is a button on my profile that allows for donations. However, just so you know, this is only a project I work on in my free time so money/donations have no bearing on updates, support, or whatever else, so don't feel obligated to spend money on this.

**Comment by craigers521** [comment]
Nice dude! Check your donations. 😎 It's not much but i appreciate the work you have done!
