### ISSUE TITLE
It just not working (Self-hosted - Script on index.html)

### ISSUE THREAD

**Issue by tr1p0p** [nicknsy/jellyscrub#91]
So, it's been a week it install this extension but i thin it just... doesn't do nothing ?

BIF is generated, i followed instruction, edit index.html, nothing.

I have a selfhosted jellyfin install with yunohost on a x86_64 computer, i don't know why it's just not working, logs show still error on script injection despite the fact it's in index.html.

Don't show nothing about this on logs, on dev log on my browser. So it's pretty confusing.

Any help on this ? Is this issue with my installation ?

**Comment by nicknsy** [comment]
They plugin will not log an error if it finds the script injected in the index.html, so it sounds like it was not correctly put in.

Could you paste the part where you injected the script as well as the some of the surrounding html? Could you also post the error logged by jellyscrub?

**Comment by tr1p0p** [comment]
Well i just edit with nano the index.html from `/usr/share/jellyfin/web` folder. I could give you the index.html file here but it's not very hard to just put a line on  a .html files so it's weird.

It's also talk about permission error.

Here logs around this, and index.html code : 

index.html
 ```<body>
																							<div class="backdropContainer"/>
																							<div class="backgroundContainer"/>
																							<div class="mainDrawer hide">
																								<div class="mainDrawer-scrollContainer scrollContainer focuscontainer-y"/>
																							</div>
																							<div class="skinHeader focuscontainer-x"/>
																							<div class="mainAnimatedPages skinBody">
																								<div class="splashLogo"/>
																							</div>
																							<div class="mainDrawerHandle"/>
																							<script plugin="Jellyscrub" version="1.0.0.0" src="/Trickplay/ClientScript"/>
																						</body>
																					</html>```

logs :

Hum, it don't find log around jellyscrub anymore...

**Comment by nicknsy** [comment]
If you access jellyfin from an incognito window or if you follow the last step in the README to use jellyscrub on the desktop client does anything change?

**Comment by tr1p0p** [comment]
Hum, so i confirm it work with jellyfin media player. So it's on my self-hosted server side, i guess. Weird. 

I close then it's not on your side, thanks for the help, and this extension.

**Comment by cdgiguere** [comment]
@tr1p0p did you find a solution for this? I am having the same issue. Getting the permissions error in logs even though I put the script block in the same place. If I open an incognito browser the plugin works great, but no matter how many times I clear the site data it won't work on non-incognito FireFox.
